global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['54.242.116.74:8081']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['54.242.116.74:9093']

rule_files:
  - 'alert.rules'

alerts:
  groups:
    - name: container_alerts
      rules:
        - alert: ContainerDown
          expr: up{job="cadvisor"} == 0
          for: 10s
          labels:
            severity: critical
          annotations:
            summary: "Container {{ $labels.instance }} is down"
            description: "The container has been down for more than 10 seconds."
